### ISSUE TITLE
Execute python script.

### ISSUE THREAD

**Issue by ghost** [rolfa/calendar-search#1]
In the sailfish OS terminal i activate sudo, install sudo and install nano, then created a calendar-search.py file and copied it into the root directory.

When i enter:

List all entries: sudo calendar-search.py "%"

it says bash: List: command not found.

Can you briefly describe how to run the python script in the terminal? Am i required to install a linux python distro on the sailfish phone? Which one?

**Comment by smyru** [comment]
Try: sudo python calendar-search.py "%"

**Comment by rolfa** [comment]
- make sure the script has execute permissions: "chmod +x calendar-search.py"
- make sure python 2 is installed: "python" should output "Python 2.7.9 ..." or similar
- both "sudo calendar-search.py" and "sudo python calendar-search.py" work
- if python is installed, this would output a few lines: "pkcon search name python | grep Installed"
- see also: https://together.jolla.com/question/134395/install-python-on-jolla/

**Comment by ghost** [comment]
@rolfa @smyru thanks for the feedback, i had to copy the .py file into /home/nemo , i didnt know what my python home directory was and with the error below i figured it out.
[root@localhost nemo]# chmod +x calendar-search.py
chmod: cannot access `calendar-search.py': No such file or directory

**Comment by ghost** [comment]
now when running it returns hits properly! thanks
