### ISSUE TITLE
SyntaxError on Xperia X

### ISSUE THREAD

**Issue by matzgewinn** [rolfa/calendar-search#2]
Installed calendar-search.py succesfully on a friends Xperia X last year. This was the free version of sailfish Os for the device. After updating to the pay-version (3.2.1.20 (Nuuksio)) the command "sudo python calendar-search.py" gives an error:
"calendar-search.py, linie 7 <DOCTYPE html>
SyntaxError: invalid syntax"

I repeated the installationprocess, did a "pckon-refresh", installed python and python3 again, but it didn't work.
I am sorry, I'm not a developer, just an enthusiastic linux user, can you fix this or give me advice to fix it? Do I have to modify the script?
best regards

**Comment by rolfa** [comment]
Sorry for the late reply.
I made a few changes to make it run with Python3.
Use it as follows: sudo calendar-search.py
Let me know if it works for you.

**Comment by rolfa** [comment]
Use it as follows: sudo ./calendar-search.py

**Comment by matzgewinn** [comment]
Thank You very much - this did it. Would it work with devel-su as well?

best regards and thank you for your work!

**Comment by matzgewinn** [comment]
can I buy you a cup of coffee??

**Comment by rolfa** [comment]
Enjoy the script - no need to pay me anything.

**Comment by matzgewinn** [comment]
Hello dear rolfa,

sorry for opening this issue again - or should I open a new one? - not sure...

Whatever: After updgrading on sailfish os 4 a few days ago, there is an error appearing after running the script:


"File "calendar-search.py", line 52, in <module>

import os, sys, sqlite3

ImportError: No module named sqlite3"

What does that mean and do you have an idea how to fix this?

Best regards!

**Comment by matzgewinn** [comment]
I opened a new issue.
